### ISSUE TITLE
The "Array Sources" field can freeze Cytoscape

### ISSUE THREAD

**Issue by mikekucera** [RBVI/clusterMaker2#5]
Open the tunable dialog for one of the algorithms that has an Array Sources field (such as Fuzzy C-means). Select something in the dropdown list. Cytoscape freezes.

This seems to only happen when the dropdown initially says "--None--". I tried this on two separate computers and was able to reproduce it on both.

Cytoscape 3.4
clusterMaker2 0.9.5.

**Comment by scootermorris** [comment]
Mike -- I can't reproduce this with a small sample network I have.  Do you have a network that exhibits the problem?
